# Generated by Django 4.2.5 on 2024-01-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='caregory_name',
            new_name='category_name',
        ),
    ]
